basePath: /
host: 127.0.0.1:8080
info:
  contact: {}
  description: API para gerenciamento de usuários e tarefas usando GIN e Mongodb
  title: API de Autenticação e Tarefas
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    description: 'Value: Bearer abc... (Bearer+space+token)'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
